import os
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from typing import Any, Dict, Optional

import requests


class PaystackService:
    """
    Service class for interacting with the Paystack API.

    Monetary amounts passed to initiate_payment() are expected
    to be in Nigerian Naira (NGN), not kobo.

    Example:
        amount=2500.00
        -> Paystack receives 250000 kobo.
    """

    def __init__(self) -> None:
        self.secret_key = os.environ.get("PAYSTACK_SECRET_KEY")
        self.public_key = os.environ.get("PAYSTACK_PUBLIC_KEY")
        self.base_url = "https://api.paystack.co"

        if not self.secret_key:
            raise ValueError(
                "PAYSTACK_SECRET_KEY environment variable is required"
            )

        self.headers = {
            "Authorization": f"Bearer {self.secret_key}",
            "Content-Type": "application/json",
        }

    @staticmethod
    def _error_response(message: str) -> Dict[str, Any]:
        """Return a consistent failed-service response."""
        return {
            "status": False,
            "message": message,
            "data": {},
        }

    @staticmethod
    def _success_response(
        message: str,
        data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Return a consistent successful-service response."""
        return {
            "status": True,
            "message": message,
            "data": data or {},
        }

    @staticmethod
    def _convert_naira_to_kobo(amount: Any) -> int:
        """
        Convert an NGN amount to kobo safely.

        Raises:
            ValueError: If the amount is invalid or not greater than zero.
        """
        try:
            amount_naira = Decimal(str(amount))
        except (InvalidOperation, ValueError, TypeError):
            raise ValueError("Invalid payment amount.")

        if not amount_naira.is_finite():
            raise ValueError("Payment amount must be a finite number.")

        if amount_naira <= 0:
            raise ValueError(
                "Payment amount must be greater than zero."
            )

        amount_in_kobo = (
            amount_naira * Decimal("100")
        ).quantize(
            Decimal("1"),
            rounding=ROUND_HALF_UP,
        )

        if amount_in_kobo <= 0:
            raise ValueError(
                "Payment amount must be greater than zero."
            )

        return int(amount_in_kobo)

    @staticmethod
    def _parse_json_response(
        response: requests.Response,
    ) -> Dict[str, Any]:
        """
        Safely parse a Paystack HTTP response as JSON.

        Raises:
            ValueError: If Paystack returns invalid/non-JSON content.
        """
        try:
            data = response.json()
        except ValueError as exc:
            raise ValueError(
                "Paystack returned a non-JSON response."
            ) from exc

        if not isinstance(data, dict):
            raise ValueError(
                "Paystack returned an unexpected response format."
            )

        return data

    def initiate_payment(
        self,
        email: str,
        amount: Any,
        reference: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Initialize a Paystack transaction.

        Args:
            email:
                Customer's email address.

            amount:
                Payment amount in Nigerian Naira (NGN).
                Example: 2500.00

            reference:
                Unique transaction reference generated by your application.

            metadata:
                Optional metadata associated with the transaction.

        Returns:
            A dictionary containing:
                status
                message
                data
        """

        if not isinstance(email, str) or not email.strip():
            return self._error_response(
                "Customer email is required."
            )

        if not isinstance(reference, str) or not reference.strip():
            return self._error_response(
                "Payment reference is required."
            )

        reference = reference.strip()
        email = email.strip()

        try:
            amount_in_kobo = self._convert_naira_to_kobo(amount)
        except ValueError as exc:
            return self._error_response(str(exc))

        if metadata is not None and not isinstance(metadata, dict):
            return self._error_response(
                "Payment metadata must be a dictionary."
            )

        url = f"{self.base_url}/transaction/initialize"

        payload = {
            "email": email,
            "amount": amount_in_kobo,
            "reference": reference,
            "currency": "NGN",
            "metadata": metadata or {},
        }

        try:
            response = requests.post(
                url,
                json=payload,
                headers=self.headers,
                timeout=30,
            )

        except requests.exceptions.Timeout:
            return self._error_response(
                "Payment request timed out. Please try again."
            )

        except requests.exceptions.ConnectionError:
            return self._error_response(
                "Could not connect to the payment service. "
                "Please check your internet connection and try again."
            )

        except requests.exceptions.RequestException as exc:
            return self._error_response(
                f"Payment network error: {str(exc)}"
            )

        try:
            response_data = self._parse_json_response(response)
        except ValueError as exc:
            return self._error_response(
                f"{str(exc)} HTTP status: {response.status_code}."
            )

        if response.status_code != 200:
            return self._error_response(
                response_data.get(
                    "message",
                    (
                        "Payment initialization failed. "
                        f"HTTP status: {response.status_code}."
                    ),
                )
            )

        if not response_data.get("status"):
            return self._error_response(
                response_data.get(
                    "message",
                    "Payment initialization failed.",
                )
            )

        payment_data = response_data.get("data")

        if not isinstance(payment_data, dict):
            return self._error_response(
                "Paystack returned an invalid payment response."
            )

        authorization_url = payment_data.get("authorization_url")

        if not isinstance(authorization_url, str) or not authorization_url.strip():
            return self._error_response(
                "Payment was initialized but no payment URL was returned."
            )

        return self._success_response(
            response_data.get(
                "message",
                "Payment initialized successfully.",
            ),
            payment_data,
        )

    def verify_payment(
        self,
        reference: str,
    ) -> Dict[str, Any]:
        """
        Verify a Paystack transaction using its reference.

        This method confirms that Paystack reports the transaction
        status as 'success'.

        IMPORTANT:
        The caller should additionally validate:
            - reference
            - amount
            - currency
            - order/customer association
            - whether the order has already been fulfilled
        """

        if not isinstance(reference, str) or not reference.strip():
            return self._error_response(
                "Payment reference is required."
            )

        reference = reference.strip()

        url = f"{self.base_url}/transaction/verify/{reference}"

        try:
            response = requests.get(
                url,
                headers=self.headers,
                timeout=30,
            )

        except requests.exceptions.Timeout:
            return self._error_response(
                "Payment verification request timed out. "
                "Please try again."
            )

        except requests.exceptions.ConnectionError:
            return self._error_response(
                "Could not connect to the payment service. "
                "Please try again."
            )

        except requests.exceptions.RequestException as exc:
            return self._error_response(
                f"Payment verification network error: {str(exc)}"
            )

        try:
            response_data = self._parse_json_response(response)
        except ValueError as exc:
            return self._error_response(
                f"{str(exc)} HTTP status: {response.status_code}."
            )

        if response.status_code != 200:
            return self._error_response(
                response_data.get(
                    "message",
                    (
                        "Payment verification failed. "
                        f"HTTP status: {response.status_code}."
                    ),
                )
            )

        if not response_data.get("status"):
            return self._error_response(
                response_data.get(
                    "message",
                    "Payment verification failed.",
                )
            )

        transaction_data = response_data.get("data")

        if not isinstance(transaction_data, dict):
            return self._error_response(
                "Paystack returned an invalid transaction response."
            )

        transaction_status = transaction_data.get("status")

        if transaction_status != "success":
            return {
                "status": False,
                "message": (
                    "Payment was not successful. "
                    f"Status: {transaction_status or 'unknown'}"
                ),
                "data": transaction_data,
            }

        return self._success_response(
            "Payment verified successfully.",
            transaction_data,
        )

    def create_transfer_recipient(
        self,
        name: str,
        account_number: str,
        bank_code: str,
    ) -> Dict[str, Any]:
        """
        Create a Paystack transfer recipient.

        This is for transfers/disbursements, not customer
        payment verification.
        """

        if not isinstance(name, str) or not name.strip():
            return self._error_response(
                "Recipient name is required."
            )

        if not isinstance(account_number, str) or not account_number.strip():
            return self._error_response(
                "Recipient account number is required."
            )

        if not isinstance(bank_code, str) or not bank_code.strip():
            return self._error_response(
                "Recipient bank code is required."
            )

        url = f"{self.base_url}/transferrecipient"

        payload = {
            "type": "nuban",
            "name": name.strip(),
            "account_number": account_number.strip(),
            "bank_code": bank_code.strip(),
            "currency": "NGN",
        }

        try:
            response = requests.post(
                url,
                json=payload,
                headers=self.headers,
                timeout=30,
            )

        except requests.exceptions.Timeout:
            return self._error_response(
                "Transfer recipient request timed out. "
                "Please try again."
            )

        except requests.exceptions.ConnectionError:
            return self._error_response(
                "Could not connect to the payment service. "
                "Please try again."
            )

        except requests.exceptions.RequestException as exc:
            return self._error_response(
                f"Transfer recipient network error: {str(exc)}"
            )

        try:
            response_data = self._parse_json_response(response)
        except ValueError as exc:
            return self._error_response(
                f"{str(exc)} HTTP status: {response.status_code}."
            )

        if response.status_code != 200:
            return self._error_response(
                response_data.get(
                    "message",
                    (
                        "Failed to create transfer recipient. "
                        f"HTTP status: {response.status_code}."
                    ),
                )
            )

        if not response_data.get("status"):
            return self._error_response(
                response_data.get(
                    "message",
                    "Failed to create transfer recipient.",
                )
            )

        recipient_data = response_data.get("data")

        if not isinstance(recipient_data, dict):
            return self._error_response(
                "Paystack returned an invalid transfer recipient response."
            )

        return self._success_response(
            response_data.get(
                "message",
                "Transfer recipient created successfully.",
            ),
            recipient_data,
        )